name: "zigbee2mqtt"

services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=${TZ}
    devices:
      - /dev/serial/by-id/${ZIGBEE_STICK_SERIAL}:/dev/ttyACM0
    labels:
      - homepage.group=Smart Home
      - homepage.name=Zigbee2MQTT
      - homepage.icon=zigbee2mqtt.svg
      - homepage.href=https://z2m.seq.${DOMAIN}
      - homepage.description=Sequoia Zigbee handler
    ports:
      - ${PORT_ZIGBEE2MQTT:-8085}:8080  # <Host Port>:<Container Port>